jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        MensaBattle\FacebookAppBundle\Security\User\FacebookProvider: sha512
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        facebook_provider:
            id: facebook_user_provider

    firewalls:
        main:
            pattern: ^/.*
            fos_facebook:
                app_url: "%facebook_app%"
                server_url: "%facebook_server%"
                login_path: /
                check_path: /login_check
                default_target_path: /
                provider: facebook_provider
            logout:
                path: /logout
            anonymous: true
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }